// Central config for dashboard panel buttons, routes, roles, and permissions
import { BookOpen, ClipboardList, Wrench, Utensils, Users, HelpCircle, BarChart3, FileText, Folder, Bell, Settings } from 'lucide-react';

export type UserRole = 'admin' | 'teacher' | 'student' | 'parent' | 'hizmetli';

export interface DashboardButton {
  key: string;
  title: string;
  description: string;
  route: string;
  roles: UserRole[]; // Who can see this button
  crudRoles?: UserRole[]; // Who can add/edit/delete (if different from view)
  icon?: React.ElementType;
  color?: string; // Optional color property for button styling
  showForDormitory?: boolean; // Only show for students with pansiyon=true
  actionText?: string; // Custom action text for the button
}

export const dashboardButtons: DashboardButton[] = [
  // STUDENT PRIORITY BUTTONS (Most Important First)
  {
    key: 'assignments-student',
    title: 'Ödevler',
    description: 'Ödevlerini takip et',
    route: '/student/odevler',
    roles: ['student'],
    icon: BookOpen,
    color: 'rose',
    actionText: 'Görüntüle',
  },
  {
    key: 'lesson-schedule-student',
    title: 'Ders Programı',
    description: 'Ders programını görüntüle',
    route: '/student/ders-programi',
    roles: ['student'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Programı Gör',
  },
  {
    key: 'grades-student',
    title: 'Notlarım',
    description: 'Notlarını görüntüle',
    route: '/student/notlar',
    roles: ['student'],
    icon: BookOpen,
    color: 'rose',
    actionText: 'Notlarımı Gör',
  },
  {
    key: 'announcements-student',
    title: 'Duyurular',
    description: 'Tüm duyuruları görüntüle',
    route: '/student/duyurular',
    roles: ['student'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Duyuruları Gör',
  },
  {
    key: 'my-clubs-student',
    title: 'Kulüplerim',
    description: 'Katıldığın kulüpleri görüntüle',
    route: '/student/kuluplerim',
    roles: ['student'],
    icon: Users,
    color: 'rose',
    actionText: 'Kulüplerimi Gör',
  },
  {
    key: 'student-evci',
    title: 'Evci Bilgilerim',
    description: 'Evci bilgilerini görüntüle',
    route: '/student/evci',
    roles: ['student'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Bilgilerimi Gör',
  },

  // Dormitory related buttons (only for students with pansiyon=true)
  {
    key: 'student-meal-list',
    title: 'Yemek Listesi',
    description: 'Pansiyon yemek menüsünü görüntüle',
    route: '/student/yemek-listesi',
    roles: ['student'],
    showForDormitory: true,
    icon: Utensils,
    color: 'rose',
    actionText: 'Menüyü Gör',
  },
  {
    key: 'student-supervisor-list',
    title: 'Belletmen Listesi',
    description: 'Pansiyon belletmenlerini görüntüle',
    route: '/student/belletmen-listesi',
    roles: ['student'],
    showForDormitory: true,
    icon: Users,
    color: 'rose',
    actionText: 'Listeyi Gör',
  },
  {
    key: 'student-maintenance-request',
    title: 'Bakım talepleri',
    description: 'Oda bakım talebi oluştur',
    route: '/student/bakim-talepleri',
    roles: ['student'],
    showForDormitory: true,
    icon: Wrench,
    color: 'rose',
    actionText: 'Talep Oluştur',
  },

  // TEACHER PRIORITY BUTTONS
  {
    key: 'teacher-students',
    title: 'Öğrencilerim',
    description: 'Öğrenci bilgilerini görüntüle',
    route: '/teacher/ogrencilerim',
    roles: ['teacher'],
    icon: Users,
    color: 'rose',
    actionText: 'Öğrencileri Gör',
  },
  {
    key: 'teacher-assignments',
    title: 'Ödevler',
    description: 'Ödev oluştur ve yönet',
    route: '/teacher/odevler',
    roles: ['teacher'],
    icon: BookOpen,
    color: 'rose',
    actionText: 'Ödevleri Yönet',
  },
  {
    key: 'teacher-grades',
    title: 'Notlar',
    description: 'Öğrenci notlarını gir ve düzenle',
    route: '/teacher/notlar',
    roles: ['teacher'],
    icon: BookOpen,
    color: 'rose',
    actionText: 'Notları Gir',
  },
  {
    key: 'teacher-schedule',
    title: 'Ders Programı',
    description: 'Ders programını görüntüle',
    route: '/teacher/ders-programi',
    roles: ['teacher'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Programı Gör',
  },
  {
    key: 'teacher-announcements',
    title: 'Duyurular',
    description: 'Duyuruları yönet ve yayınla',
    route: '/teacher/duyurular',
    roles: ['teacher'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Duyuruları Yönet',
  },

  // PARENT PRIORITY BUTTONS
  {
    key: 'assignments-parent',
    title: 'Ödevler',
    description: 'Çocuğunun ödevlerini takip et',
    route: '/parent/odevler',
    roles: ['parent'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Ödevleri Takip Et',
  },
  {
    key: 'lesson-schedule-parent',
    title: 'Ders Programı',
    description: 'Çocuğunun ders programını görüntüle',
    route: '/parent/ders-programi',
    roles: ['parent'],
    icon: BookOpen,
    color: 'rose',
    actionText: 'Programı Gör',
  },
  {
    key: 'grades-parent',
    title: 'Notlar',
    description: 'Çocuğunun notlarını görüntüle',
    route: '/parent/notlar',
    roles: ['parent'],
    icon: BookOpen,
    color: 'rose',
    actionText: 'Notları Gör',
  },
  {
    key: 'announcements-parent',
    title: 'Duyurular',
    description: 'Tüm duyuruları görüntüle',
    route: '/parent/duyurular',
    roles: ['parent'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Duyuruları Gör',
  },
  {
    key: 'my-clubs-parent',
    title: 'Kulüplerim',
    description: 'Çocuğunun kulüplerini görüntüle',
    route: '/parent/kuluplerim',
    roles: ['parent'],
    icon: Users,
    color: 'rose',
    actionText: 'Kulüpleri Gör',
  },
  {
    key: 'parent-evci',
    title: 'Evci Bilgileri',
    description: 'Çocuğunun evci bilgilerini görüntüle',
    route: '/parent/evci',
    roles: ['parent'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Bilgileri Gör',
  },

  // Admin & Hizmetli
  {
    key: 'meal-list',
    title: 'Pansiyon Yemek Listesi',
    description: 'Aylık yemek menüsünü görüntüle ve düzenle',
    route: '/admin/yemek-listesi',
    roles: ['admin', 'hizmetli'],
    crudRoles: ['admin', 'hizmetli'],
    icon: BookOpen,
    color: 'rose',
    actionText: 'Menüyü Yönet',
  },
  // Belletmen Listesi (separate for admin and hizmetli)
  {
    key: 'supervisor-list-admin',
    title: 'Pansiyon Belletmen Listesi',
    description: 'Belletmen nöbet listelerini yönet',
    route: '/admin/belletmen-listesi',
    roles: ['admin'],
    crudRoles: ['admin'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Listeyi Yönet',
  },
  {
    key: 'supervisor-list-hizmetli',
    title: 'Pansiyon Belletmen Listesi',
    description: 'Belletmen nöbet listelerini yönet',
    route: '/hizmetli/belletmen-listesi',
    roles: ['hizmetli'],
    crudRoles: ['hizmetli'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Listeyi Yönet',
  },
  {
    key: 'maintenance-requests',
    title: 'Oda Bakım-Onarım Talepleri',
    description: 'Bakım taleplerini görüntüle ve yönet',
    route: '/admin/bakim-talepleri',
    roles: ['admin', 'hizmetli'],
    crudRoles: ['admin', 'hizmetli'],
    icon: Wrench,
    color: 'rose',
    actionText: 'Talepleri Yönet',
  },
  // Admin only
  {
    key: 'admin-clubs',
    title: 'Kulüpler',
    description: 'Tüm kulüpleri yönet',
    route: '/admin/kulupler',
    roles: ['admin'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Kulüpleri Yönet',
  },
  {
    key: 'admin-notifications',
    title: 'Bildirim Yönetimi',
    description: 'Bildirimleri oluştur ve yönet',
    route: '/admin/bildirimler',
    roles: ['admin', 'teacher'],
    icon: Bell,
    color: 'rose',
    actionText: 'Bildirimleri Yönet',
  },
  {
    key: 'admin-notification-automation',
    title: 'Bildirim Otomasyonu',
    description: 'Otomatik bildirim kurallarını yönet',
    route: '/admin/bildirim-otomasyonu',
    roles: ['admin', 'teacher'],
    icon: Settings,
    color: 'rose',
    actionText: 'Otomasyonu Yönet',
  },
  {
    key: 'admin-evci-list',
    title: 'Evci Listesi',
    description: 'Evci öğrencileri yönet',
    route: '/admin/evci-listesi',
    roles: ['admin'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Listeyi Yönet',
  },
  {
    key: 'assignments-admin',
    title: 'Ödevler',
    description: 'Tüm ödevleri görüntüle',
    route: '/admin/odevler',
    roles: ['admin'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Ödevleri Gör',
  },
  {
    key: 'announcements-admin',
    title: 'Duyurular',
    description: 'Tüm duyuruları görüntüle',
    route: '/admin/duyurular',
    roles: ['admin'],
    icon: ClipboardList,
    color: 'rose',
    actionText: 'Duyuruları Gör',
  },
  {
    key: 'sync',
    title: 'Senkronizasyon',
    description: 'Veri senkronizasyon işlemleri',
    route: '/admin/senkronizasyon',
    roles: ['admin'],
    icon: Wrench,
    color: 'rose',
    actionText: 'Senkronize Et',
  },
  // Analytics ve Raporlama
  {
    key: 'analytics-dashboard',
    title: 'Analytics Dashboard',
    description: 'Sistem analitikleri ve istatistikler',
    route: '/admin/analytics',
    roles: ['admin', 'teacher'],
    icon: BarChart3,
    color: 'rose',
    actionText: 'Analizleri Gör',
  },
  {
    key: 'report-management',
    title: 'Rapor Yönetimi',
    description: 'Raporları oluştur ve yönet',
    route: '/admin/reports',
    roles: ['admin', 'teacher'],
    icon: FileText,
    color: 'rose',
    actionText: 'Raporları Yönet',
  },
  // Dosya Yönetimi Sistemi (Sadece Admin)
  {
    key: 'file-management',
    title: 'Dosya Yönetimi',
    description: 'Dosyaları ve klasörleri yönet',
    route: '/admin/dosyalar',
    roles: ['admin'],
    icon: Folder,
    color: 'rose',
    actionText: 'Dosyaları Yönet',
  },
];
