apiVersion: apps/v1
kind: Deployment
metadata:
  name: tofas-backend
  namespace: tofas-fen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tofas-backend
  template:
    metadata:
      labels:
        app: tofas-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-username/tofas-fen-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: tofas-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: tofas-config
              key: PORT
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: tofas-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tofas-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: tofas-secrets
              key: JWT_REFRESH_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ghcr-secret