#!/usr/bin/env bash
# Update Kubernetes secrets from .new_secrets.env (local file generated by generate_secrets.ps1)
# This script reads .new_secrets.env and creates/updates k8s secrets. It does NOT store secrets in repo.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS_FILE="$ROOT_DIR/.new_secrets.env"

if [ ! -f "$SECRETS_FILE" ]; then
  echo ".new_secrets.env not found. Run scripts/generate_secrets.ps1 first to create it (locally)."
  exit 1
fi

echo "Loading secrets from $SECRETS_FILE (local only)"
set -a
source "$SECRETS_FILE"
set +a

# Example: update jwt-secret in the tofas-fen namespace
kubectl create secret generic jwt-secret \
  --namespace=tofas-fen \
  --from-literal=secret="$JWT_SECRET" \
  --from-literal=refresh-secret="$JWT_REFRESH_SECRET" \
  --dry-run=client -o yaml | kubectl apply -f -

# Update mongodb-secret (stringData style) - if your cluster expects a different key name adjust accordingly
kubectl create secret generic mongodb-secret \
  --namespace=tofas-fen \
  --from-literal=mongo-password="$MONGO_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl create secret generic redis-secret \
  --namespace=tofas-fen \
  --from-literal=password="$REDIS_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "Kubernetes secrets updated (applied). Verify pods need restart depending on your deployment strategy."
